name: madidou
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev.
# Remove this line if you wish to publish to pub.dev.
publish_to: "none"

# Version and build number configuration. Can be overridden during the build process.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  firebase_analytics: ^10.8.8
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_bloc: ^8.1.4
  http: ^1.2.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  firebase_storage: ^11.6.10
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  rive: ^0.13.1
  flutter_svg: ^1.1.6
  intl: ^0.19.0
  flutter_xlider: ^3.5.0
  carousel_slider: ^4.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_osm_plugin: ^0.70.4
  url_launcher: ^6.2.6
  percent_indicator: ^4.2.3
  file_picker: ^8.0.3
  table_calendar: ^3.1.2
  flutter_pdfview: ^1.3.2
  webview_flutter: ^4.7.0
  advance_pdf_viewer2: ^2.0.5+1
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  socket_io_client: ^2.0.3+1
  flutter_spinkit: ^5.2.1
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/logo/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
