name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v3

      # Step 2: Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Step 3: Get Flutter dependencies
      - run: flutter pub get

      # Step 4: Ensure no platform-incompatible code is included in the build
      - name: Check Platform Compatibility
        run: |
          if grep -R "import 'package:win32/win32.dart';" lib/; then
            echo "Error: Win32 package is not compatible with iOS."
            exit 1
          fi

      # Step 5: Update iOS dependencies using CocoaPods
      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      # Step 6: Build the iOS app without code signing
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      # Step 7: Create a Payload directory and move the Runner.app
      - name: Prepare IPA Payload
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
        working-directory: build/ios/iphoneos

      # Step 8: Zip the Payload to create an IPA file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Step 9: Upload the IPA file to GitHub Releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
